### PR TITLE
Randomalt post

### PR DESCRIPTION
**Pull request by rbreesems**
This merge requests adds two things:

a. Extends the browser `randomalt` command in `BaseBrowserHandler.cs` to look for `gf` elements in forms, if one is found, then look for input elements inside and post corpus text to those input elements. It is assumed that the pages generated with `gf` elements are intended as targets for POST traffic.  This is an effort to generate more POST traffic during normal web browsing. This will probably be tweaked more in the future. 

b. A Pidgin client handler was added, see `Handlers\Pidgin.cs` - Pidgin is a chat client that can be configured for different protocols. This was tested with  Windows 10 Pidgin 2.14.1 (libpurple 2.14.1) and Centos 7.3 ejabberd server. See the comments in  `Handlers\Pidgin.cs`  for prerequisites and assumptions.

FYI, I had to add AutoIt as a package dependency. I had to use a combination of AutoIt and User32 calls for the window automation.

### CODE REVIEW

**Comment by sei-dupdyke** [comment]
Good to go, thanks for these features. Particularly looking forward to trying out pidgin. Will also be looking at leveraging your POST work for some social media stuff I've been working on.

**Comment by rbreesems** [comment]
Thanks for merging this.  Let me know if you have any problems testing the Pidgin addition.  Hopefully I did not leave anything out of the assumptions/prerequisites comments but who knows.

Next thing being added is a remote desktop handler, all it will do is open remote desktop to a target and move the mouse occasionally.  Our event guys use this one.

**Comment by sei-dupdyke** [comment]
I will try to get pidgin setup sometime soon. Remote desktop will be awesome.

**Comment by rbreesems** [comment]
FYI, there is a big event in March that is a repeat of one done in  late Novemeber/early December, and the goal is for traffic gen is to be 100% GHOSTS for that event.

**Comment by sei-dupdyke** [comment]
Here is to no issues!!

**Comment by sei-dupdyke** [comment]
> I was just gonna ask if social media / blog posting is possible. Great stuff!

One of the weird things I have found is that there is very little support in the browser for POST|PUT|DELETE requests without some sort of form GET prior. I had originally went down a road where I would just generate a post request and send it, but I think I am going to go @rbreesems' route of getting a form first.

**Pull request merged**
