### PR TITLE
Style: Format C# and Python Code for Improved Clarity

### PR DESCRIPTION
**Pull request by dh4340**
In my updates, I formatted all possible C# code using the `dotnet` tool, enhancing both readability and consistency. Although a few build issues have arisen so I couldn't format all the code, the overall formatting adjustments have significantly improved the code's clarity.

For Python, I utilized **Ruff** with the `check --fix` command to format the code. This process led to the removal of many unnecessary imports, as it’s unnecessary to include dependencies for functions that are imported from elsewhere. 

While I have not tested the functionality of the code after these changes, I can confirm that they primarily focused on formatting. The only exception is the resolution of a bare `except` statement I identified in `app.py`, which I have since fixed in this merge request.

### CODE REVIEW

**Comment by dh4340** [comment]
Sorry if i'm doing to much let me know, I love the project and want to help where I can. I am mainly a Python specialist but loving learning C#.

**Comment by sei-dupdyke** [comment]
No, its great, my only complaint is that it takes significant time to review 118 files changed, but I'll get it done.

**Comment by sei-dupdyke** [comment]
So, the problem is that GHOSTS is a monorepo with lots of projects within it — and this PR spans many of them, making it supremely difficult for me to manage. Can I ask that you break this up into several PRs broken up across src/<sub_folder> please?

**Comment by dh4340** [comment]
Yea course i will do it one by one happily. I'll sort that next week

**Pull request closed without merging**
