### PR TITLE
Transition to Async Framework and Enhance Server Modularity in Ghosts Pandora

### PR DESCRIPTION
**Pull request by dh4340**
**Transition to Async Framework and Enhance Server Modularity in Ghosts Pandora**

**Summary:**
This merge request implements critical enhancements to the server code for the Ghosts Pandora project, focusing on moving to an asynchronous framework, improving modularisation, and integrating video streaming capabilities. Key modifications include:

1. **Transition to Async Framework:** Shifted the server to an asynchronous framework, enabling non-blocking operations and enhancing the overall performance and responsiveness of the server.
2. **Improved Modularisation:** Refactored the codebase into distinct modules, promoting better organisation and ease of maintenance. This modular approach simplifies updates and debugging, allowing for more efficient development processes.
3. **Integration of Video Streaming:** Added functionality for video streaming, expanding the server's capabilities to serve multimedia content dynamically alongside traditional file types.
4. **Ollama Integration:** Integrated Ollama into most endpoints, allowing for advanced content generation and dynamic responses throughout the server.
5. **API Documentation Generation:** Implemented automatic generation of API documentation (Swagger) accessible at the `/docs` endpoint, providing clear and comprehensive documentation for all API routes.
6. **Import Statements:** Refined the use of existing imports (zipstream, docx, PIL, pptx) to enhance code efficiency.
7. **Class Attributes:** Introduced new class attributes (`request_url`, `file_requested`) for better organisation and clarity.
8. **Expanded HTTP Method Support:** Introduced additional HTTP methods (PUT, DELETE) for comprehensive request handling.
9. **Enhanced Response Handling:** Improved mechanisms to accommodate various content types (ZIP, binary, JSON, CSV, DOCX, PPTX, XLSX) with encapsulated logic through methods like `return_zip`, `return_binary`, and `return_image`.
10. **Improved Error Handling:** Enhanced error logging for specific exception feedback.
11. **Dynamic Content Generation:** Integrated Faker alongside Ollama for generating a broader array of random data, enriching server responses.
12. **Dynamic File Handling:** Eliminated hard-coded paths for more dynamic file serving and payload handling.
13. **Expanded Documentation:** Provided detailed usage instructions, including supported file types and error responses.

### CODE REVIEW

**Comment by dh4340** [comment]
Currently working on adding in Ollama, it is now functional most routes.

**Comment by dh4340** [comment]
@dustinupdyke wondered if you had a chance to take a look at the this and just give me an idea if its useful/wanted.

**Comment by sei-dupdyke** [comment]
Grr, now all kinds of reference errors. 

no module named routes
no module named app_logging

**Comment by sei-dupdyke** [comment]
uvicorn app:app can't possibly work.

**Comment by sei-dupdyke** [comment]
found hints in the dockerfile

**Comment by sei-dupdyke** [comment]
crisis averted.

**Comment by sei-dupdyke** [comment]
I cleaned up html, css, and js.

**Comment by sei-dupdyke** [comment]
Otherwise, awesome job, thank you!

**Pull request merged**
